encoding: utf-8

# SEO相关信息
title: UMaize                               # 站的标题
description: A Jekyll Theme.                # 站的描述
keywords: moimo,thoughts,scripts,Python     # 站的关键词，（ASCII）逗号分隔
author: moimo233                            # 站的作者

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'cli.bat', 'dist.tar.gz']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://rain.moimo.me'
baseurl: ''

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# _includes/ext-adsense.html 里面修改为自己的配置
extMTA: false

# 百度收录自动推送,不需要请设置为false
extBaidu: true

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

